# -----------------------------
# This is a basic workflow 
# -----------------------------

name: My github basics

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my-testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message on testing
      run: echo "Hello World from testing"
  
  my-deploy:
    
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      
    - name: Print Hello message on Deploy
      run: echo "Hello World from deploy"
