# -----------------------------
# This is a basic workflow 
# -----------------------------

name: My github basics
env:
  APPLICATION_NAME : "MyAPP"
  PACKAGE_NAME     : "deploy_file_ver-${{ github.sha }}"
  

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my-testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message on testing
      run: echo "Hello World from testing"
    
    - name: Execute few command
      run: 
         echo "Message 1"
         echo "Message 2"
         echo "Application name ${{ env.APPLICATION_NAME }}"
   
    - name: Git clone my repo
      uses: actions/checkout@v1
         
    - name: List curr folder
      run: ls -al
        
  my-deploy:
    
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      
    - name: Print Hello message on Deploy
      run: echo "Hello World from deploy"
    - name: Printing deploy package name
      run:  echo "Deployment name ${{ env.PACKAGE_NAME }}"

    - name: Lets test some packages 1 
      run: aws --version
      
    - name: Lets test some packages 2 
      run: zip
    
