# -----------------------------
# This is a basic workflow 
# -----------------------------

name: CI my github basics

# Controls when the workflow will run
on:
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello message
      run: echo "Hello World from testing"
  
  my-deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Print Hello message
      run: echo "Hello World from deploy"
